In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv("backloggd_games.csv")
df.head()

,Unnamed: 0,Title,Release_Date,Developers,Summary,Platforms,Genres,Rating,Plays,Playing,Backlogs,Wishlist,Lists,Reviews
0,0,Elden Ring,"Feb 25, 2022","['FromSoftware', 'Bandai Namco Entertainment']","Elden Ring is a fantasy, action and open world...","['Windows PC', 'PlayStation 4', 'Xbox One', 'P...","['Adventure', 'RPG']",4.5,21K,4.1K,5.6K,5.5K,4.6K,3K
1,1,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",The Legend of Zelda: Breath of the Wild is the...,"['Wii U', 'Nintendo Switch']","['Adventure', 'Puzzle']",4.4,35K,3.1K,5.6K,3K,5.1K,3K
2,2,Hades,"Dec 07, 2018",['Supergiant Games'],A rogue-lite hack and slash dungeon crawler in...,"['Windows PC', 'Mac', 'PlayStation 4', 'Xbox O...","['Adventure', 'Brawler', 'Indie', 'RPG']",4.3,25K,3.5K,7.3K,4K,3.2K,2.1K
3,3,Hollow Knight,"Feb 24, 2017",['Team Cherry'],A 2D metroidvania with an emphasis on close co...,"['Windows PC', 'Mac', 'Linux', 'Nintendo Switch']","['Adventure', 'Indie', 'Platform']",4.4,25K,2.7K,9.6K,2.6K,3.4K,2.1K
4,4,Undertale,"Sep 15, 2015","['tobyfox', '8-4']","A small child falls into the Underground, wher...","['Windows PC', 'Mac', 'Linux', 'PlayStation 4'...","['Adventure', 'Indie', 'RPG', 'Turn Based Stra...",4.2,32K,728,5.7K,2.1K,3.9K,2.5K

In [6]:
df.describe()

         Unnamed: 0        Rating
count  60000.000000  25405.000000
mean   29999.500000      3.033171
std    17320.652413      0.735573
min        0.000000      0.300000
25%    14999.750000      2.600000
50%    29999.500000      3.100000
75%    44999.250000      3.500000
max    59999.000000      5.000000

In [4]:
df.isnull()

,Unnamed: 0,Title,Release_Date,Developers,Summary,Platforms,Genres,Rating,Plays,Playing,Backlogs,Wishlist,Lists,Reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,False,False,False,False,False,False,False,True,False,False,False,False,False,False
59996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
59997,False,False,False,False,False,False,False,True,False,False,False,False,False,False
59998,False,False,False,False,False,False,False,True,False,False,False,False,False,False
59999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
59995    False
59996    False
59997    False
59998    False
59999    False
Length: 60000, dtype: bool

In [8]:
df.shape

(60000, 14)

In [11]:
unique_ratings = (df["Rating"].unique())
print(unique_ratings)

[4.5 4.4 4.3 4.2 4.1 4.6 3.  3.7 3.8 3.4 2.6 3.9 4.  2.8 3.6 3.5 3.2 2.1
 3.3 2.7 3.1 1.6 2.9 2.4 2.5 1.9 nan 1.8 2.3 2.  1.4 1.1 1.5 2.2 4.8 0.8
 1.7 4.7 0.7 1.2 1.3 5.  1.  0.9 4.9 0.3 0.5 0.6]

In [13]:
df.dropna()

,Unnamed: 0,Title,Release_Date,Developers,Summary,Platforms,Genres,Rating,Plays,Playing,Backlogs,Wishlist,Lists,Reviews
0,0,Elden Ring,"Feb 25, 2022","['FromSoftware', 'Bandai Namco Entertainment']","Elden Ring is a fantasy, action and open world...","['Windows PC', 'PlayStation 4', 'Xbox One', 'P...","['Adventure', 'RPG']",4.5,21K,4.1K,5.6K,5.5K,4.6K,3K
1,1,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",The Legend of Zelda: Breath of the Wild is the...,"['Wii U', 'Nintendo Switch']","['Adventure', 'Puzzle']",4.4,35K,3.1K,5.6K,3K,5.1K,3K
2,2,Hades,"Dec 07, 2018",['Supergiant Games'],A rogue-lite hack and slash dungeon crawler in...,"['Windows PC', 'Mac', 'PlayStation 4', 'Xbox O...","['Adventure', 'Brawler', 'Indie', 'RPG']",4.3,25K,3.5K,7.3K,4K,3.2K,2.1K
3,3,Hollow Knight,"Feb 24, 2017",['Team Cherry'],A 2D metroidvania with an emphasis on close co...,"['Windows PC', 'Mac', 'Linux', 'Nintendo Switch']","['Adventure', 'Indie', 'Platform']",4.4,25K,2.7K,9.6K,2.6K,3.4K,2.1K
4,4,Undertale,"Sep 15, 2015","['tobyfox', '8-4']","A small child falls into the Underground, wher...","['Windows PC', 'Mac', 'Linux', 'PlayStation 4'...","['Adventure', 'Indie', 'RPG', 'Turn Based Stra...",4.2,32K,728,5.7K,2.1K,3.9K,2.5K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59973,59973,FIFA Manager 14,"Oct 24, 2013","['Bright Future', 'Electronic Arts']",FIFA Manager 14: Legacy Edition is a re-releas...,['Windows PC'],['Sport'],2.5,6,0,4,0,1,0
59978,59978,Super Widget,"Feb 01, 1993",[],Planet Earth is in danger from assorted villai...,['SNES'],['Platform'],2.7,23,0,4,3,10,0
59981,59981,Pizza Delivery Boy,"Apr 18, 2010",[],When three brothers mismanage their successful...,['Wii'],['Puzzle'],0.7,3,0,0,1,1,0
59996,59996,Pathfinder: Kingmaker - Definitive Edition,"Aug 18, 2020","['Owlcat Games', 'Deep Silver']",The Definitive Edition will have all of the DL...,"['PlayStation 4', 'Xbox One']","['RPG', 'Tactical']",3.7,9,0,19,1,7,1
59999,59999,Pathfinder: Kingmaker - Definitive Edition,"Aug 18, 2020","['Owlcat Games', 'Deep Silver']",The Definitive Edition will have all of the DL...,"['PlayStation 4', 'Xbox One']","['RPG', 'Tactical']",3.7,9,0,19,1,7,1

In [15]:
print(df.loc[df['Rating'].isnull()])

       Unnamed: 0                              Title  Release_Date  \
526           526                  Final Fantasy XVI  Jun 22, 2023
634           634                           Hades II           TBD
660           660            Hollow Knight: Silksong  Dec 31, 2023
663           663  Armored Core VI: Fires of Rubicon  Aug 25, 2023
688           688                   Persona 3 Reload  Dec 31, 2024
...           ...                                ...           ...
59993       59993             No Country for Old Men           TBD
59994       59994                             Sainth  Apr 11, 2008
59995       59995                     Dragon Spirits  Apr 25, 2023
59997       59997                             Sainth  Apr 11, 2008
59998       59998                     Dragon Spirits  Apr 25, 2023

                                   Developers  \
526                           ['Square Enix']
634                      ['Supergiant Games']
660                           ['Team Cherry']
663    ['Bandai Namco Games', 'FromSoftware']
688                         ['Sega', 'Atlus']
...                                       ...
59993                                      []
59994                          ['Neo Kuriyo']
59995                 ['FHNBHJ', 'indienova']
59997                          ['Neo Kuriyo']
59998                 ['FHNBHJ', 'indienova']

                                                 Summary  \
526    Final Fantasy XVI is an upcoming action role-p...
634    Battle beyond the Underworld using dark sorcer...
660    Explore a vast, haunted kingdom in Hollow Knig...
663    By combining FromSoftware’s longstanding exper...
688    Persona 3 Reload is an upcoming remake of Pers...
...                                                  ...
59993  This is a game combines SIM and SRPG. Please l...
59994  Years after the events of "Wraith", a young gi...
59995  While constantly working on a video game witho...
59997  Years after the events of "Wraith", a young gi...
59998  While constantly working on a video game witho...

                                               Platforms  \
526                      ['Windows PC', 'PlayStation 5']
634                                       ['Windows PC']
660    ['Windows PC', 'Mac', 'Linux', 'PlayStation 4'...
663    ['Windows PC', 'PlayStation 4', 'Xbox One', 'P...
688    ['Windows PC', 'PlayStation 4', 'Xbox One', 'P...
...                                                  ...
59993                                                 []
59994                                     ['Windows PC']
59995                                     ['Windows PC']
59997                                     ['Windows PC']
59998                                     ['Windows PC']

                                          Genres  Rating Plays Playing  \
526                                      ['RPG']     NaN    83      83
634                ['Adventure', 'Indie', 'RPG']     NaN    16       3
660           ['Adventure', 'Indie', 'Platform']     NaN    98       8
663                                ['Adventure']     NaN     8       5
688                                      ['RPG']     NaN    13       1
...                                          ...     ...   ...     ...
59993  ['Indie', 'RPG', 'Simulator', 'Strategy']     NaN     0       0
59994                                         []     NaN     1       0
59995                                    ['RPG']     NaN     2       0
59997                                         []     NaN     1       0
59998                                    ['RPG']     NaN     2       0

      Backlogs Wishlist Lists Reviews
526       1.2K     3.1K   509      11
634        659     1.9K   181       1
660       1.3K       4K   331      16
663        401     1.2K   248       0
688        283     1.1K   130       0
...        ...      ...   ...     ...
59993        0        0     0       0
59994        0        2     0       0
59995        1        5     3       0
59997        0        2     0       0
59998        1        5     3       0

[34595 rows x 14 columns]